feat: add typings and interfaces for Overlay Specification v1.0.0
Redocly/redocly-cli pull request #1775
Opened 2024-10-17 20:41 UTC by jeremyfiel

related #1246

## What/Why/How?

Provides typings and interfaces for a structured Overlay description per the https://github.com/OAI/Overlay-Specification

Hopefully this is the first step to providing support for this new specification!

Can't wait to see what you build! 

## Reference
https://github.com/OAI/Overlay-Specification/releases/tag/1.0.0

## Testing

## Screenshots (optional)

## Check yourself

- [ ] Code changed? - Tested with redoc/reference-docs/workflows (internal)
- [ ] All new/updated code is covered with tests
- [ ] New package installed? - Tested in different environments (browser/node)

## Security

- [X] Security impact of change has been considered
- [X] Code follows company security practices and guidelines

2024-10-27 18:32 UTC, adamaltman approved these changes

2024-10-28 14:54 UTC, jeremyfiel commented
thanks for review. I actually missed using the defined NodeType references, so I updated those.

2024-12-02 13:01 UTC, tatomyr requested changes
You are actually a step away from implementing overlays linting. All you need to do is extend `detectSpec` to recognize overlay files and add a couple of corresponding overlay sections in rules, decorators, and preprocessors. If you decide to give it a try, feel free to ping me whenever you need any guidance.

2025-02-10 01:25 UTC, jeremyfiel commented
@tatomyr  I can't get the snapshot.js to update 

these errors don't appear to be related to my updates.

2025-02-10 22:31 UTC, HCloward approved these changes
I approve of the changelog entry if you accept @tatomyr's suggestions.

2025-02-11 10:07 UTC, tatomyr approved these changes
Nice addition, thank you Jeremy!

2025-02-11 10:09 UTC, merged