feat: add redocBundleURL option
Redocly/redocly-cli pull request #1835
Opened 2024-12-19 18:20 UTC by dmosberger

## What/Why/How?

It is helpful to be able render documentation with a non-standard redoc bundle, e.g., for testing.  In theory, one could use a custom HTML template for this purpose but in practice that's not straight-forward because the template would have to be different depending on whether or not `preview-docs` or `build-docs` is run. The template would also have to include all the CSS code.

## Testing

unit tests and e2e tests all passed.

2024-12-27 11:59 UTC, tatomyr commented
Thank you @dmosberger! We'll take a look at this soon.

2025-03-03 11:13 UTC, AlexVarchuk requested changes
@dmosberger Thank you for your contribution. I left few comments.

Some time ago we deprecated this because we had too many problems where Redoc CE of version x didn't work in Redocly/cli version y. Not all versions of cli could support all versions of Redoc CE. If we want to add this option back, we want to mention that we guarantee that only the default version (installed in cli) will work as expected. 

I think we should write this in the docs or mention it somewhere else, otherwise it will be very hard to maintain.

2025-03-03 11:13 UTC, AlexVarchuk commented on packages/cli/src/commands/preview-docs/preview-server/preview-server.ts
> +    redocBundleURL?: string;
We don't want to have inside config

2025-10-23 11:44 UTC, tatomyr commented
Closing this due to inactivity.

2025-10-23 11:44 UTC, closed without merging