fix: force response headers toLowerCase per RFC2616#4.2
Redocly/redocly-cli pull request #825
Opened 2022-08-22 21:14 UTC by jeremyfiel

- all headers are considered case-insensitive per the spec.

closes:    #824

## Reference
https://www.rfc-editor.org/rfc/rfc2616.html#section-4.2

- [x] Code is linted
- [x] Tested with redoc/reference-docs/workflows
- [x] All new/updated code is covered with tests

## Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

2022-08-23 07:26 UTC, tatomyr requested changes
Thank you for contributing @jeremyfiel! 

Please check my comment.

2022-08-23 07:26 UTC, tatomyr commented on packages/core/src/rules/common/response-contains-header.ts
> +            if (!response.headers?.[expectedHeader.toLowerCase()]) {
I believe, this won't cover the case when `response.headers` keys are not in lower case itself. E.g.: 
```
response.headers == { foo: 1, BAR: 2 }
```

It looks like lowercasing the keys should help better: 
```ts
Object.keys(response.headers).some(key => key.toLowerCase() === expectedHeader.toLowerCase())
```


Also, don't you mind adding a test?

2022-09-27 12:43 UTC, AntonKozachuk commented
Hi @jeremyfiel,
We created a new PR based on this one and mentioned you as a co-author - https://github.com/Redocly/redocly-cli/pull/882
Please let us know if there's something we missed or if you have any additional comments.
Many thanks for your contribution!

2022-09-27 12:52 UTC, jeremyfiel commented
> Hi @jeremyfiel, We created a new PR based on this one and mentioned you as a co-author - #882 Please let us know if there's something we missed or if you have any additional comments. Many thanks for your contribution!

Thanks for completing it. I was traveling last week and forgot about it.   Cheers guys!

2022-09-27 12:52 UTC, closed without merging