chore: ignore discriminator error
Redocly/redocly-cli pull request #931
Opened 2022-11-11 10:52 UTC by AntonKozachuk

## What/Why/How?
We would like to temporarily ignore an error regarding the discriminator usage.

## Reference
N/a

## Testing
Locally.

## Screenshots (optional)
N/a

## Check yourself

- [ ] Code is linted
- [ ] Tested with redoc/reference-docs/workflows
- [ ] All new/updated code is covered with tests

## Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

2022-11-14 22:22 UTC, RomanHotsiy requested changes
Any tests?

2022-11-15 11:03 UTC, tatomyr commented on packages/core/src/rules/utils.ts
> +    if (e.message !== discriminatorError) {
What about `if (e.message === discriminatorError) { return }` ?

2022-11-15 11:07 UTC, tatomyr approved these changes

2022-11-15 12:20 UTC, RomanHotsiy approved these changes
The test need to be improved but let's merge and release it and then fix the test.

2022-11-15 12:20 UTC, RomanHotsiy commented on packages/core/src/rules/oas3/__tests__/no-invalid-media-type-examples.test.ts
> +  it('should not report if allOf used with discriminator', async () => {
This test needs to be improved.

2022-11-15 12:53 UTC, merged